#!/bin/bash
# --------------------------------------------------------------------------
# This script installs files and services specific to this project.
#
# Author: Bernhard Bablok
# License: GPL3
#
# Website: https://github.com/bablokb/pi-e-ink-daily
#
# --------------------------------------------------------------------------

PACKAGES="python3-pil python3-numpy python3-rpi.gpio python3-spidev python3-pip python3-tz python3-tzlocal libxslt1.1 fonts-dejavu"
PACKAGES_PIP="smbus2 inky caldav"
PROJECT="pi-e-ink-daily"

# --- basic packages   ------------------------------------------------------

check_packages() {
  local p
  for p in "$@"; do
    echo -en "Checking $p ... " >&2
    dpkg -s "$p" 2>/dev/null | grep -q "Status.*ok" || return 0
    echo "ok" >&2
  done
  return 1
}

get_new_packages() {
  local p packages
  for p in "$@"; do
    echo -en "Checking $p ... " >&2
    if dpkg -s "$p" 2>/dev/null | grep -q "Status.*ok"; then
      echo "ok" >&2
    else
      echo "not installed" >&2
      packages+=" $p"
    fi
  done
  echo "$packages"
}

install_packages() {
  new_packages=$(get_new_packages $PACKAGES)
  if [ -n "$new_packages" ]; then
    echo -e "[INFO] installing additional packages" 2>&1
    apt-get update
    apt-get -y --no-upgrade install $new_packages
  fi

  # install PIP3 packages
  [ -n "$PACKAGES_PIP" ] && pip3 --disable-pip-version-check install $PACKAGES_PIP
}

# --- install specific files   ----------------------------------------------

install_files() {
  echo -e "[INFO] installing project files" 2>&1

  rand="$RANDOM"
  if [ -f "/etc/${PROJECT}.json" ]; then
    # save current configuration
    mv "/etc/${PROJECT}.json" "/etc/${PROJECT}.json.$rand"
  fi

  for f in `find $(dirname "$0")/../files/ -type f -not -name "*.pyc"`; do
    target="${f#*files}"
    target_dir="${target%/*}"
    [ ! -d "$target_dir" ] && mkdir -p "$target_dir"
    cp "$f" "$target"
    chown root:root "$target"
  done
  chmod 755 /usr/local/bin/daily_agenda.py

  # restore old configuration
  if [ -f "/etc/${PROJECT}.json.$rand" ]; then
    mv -f "/etc/${PROJECT}.json" "/etc/${PROJECT}.json.new"
    mv "/etc/${PROJECT}.json.$rand" "/etc/${PROJECT}.json"
    echo -e "[INFO] new version of configuration file saved to: /etc/${PROJECT}.json.new" 2>&1
  fi
}

# --- configure system   ----------------------------------------------------

configure_system() {
  # update /boot/config.txt
  if ! grep -q "^dtparam=spi=on" /boot/config.txt ; then
    echo -e "[INFO] configuring spi in /boot/config.txt" 2>&1
    echo "dtparam=spi=on" >> /boot/config.txt
    echo -e "[INFO] please reboot your system" 2>&1
  fi
  if ! grep -q "^dtoverlay=gpio-poweroff" /boot/config.txt ; then
    echo -e "[INFO] configuring gpio-poweroff for GPIO4 in /boot/config.txt" 2>&1
    echo "dtoverlay=gpio-poweroff,gpiopin=4" >> /boot/config.txt
    echo -e "[INFO] please reboot your system" 2>&1
  fi
}

# --- activate service   ----------------------------------------------------

enable_services() {
  echo -e "[INFO] enabeling $PROJECT.service" 2>&1
  systemctl enable "$PROJECT.service"
}

# --- main program   --------------------------------------------------------

install_packages

install_files
configure_system
enable_services

echo "[INFO] installation completed"
